name: Run tests

# Controls when the action will run. Triggers the workflows on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Build
        run: npm install
      - name: test
        run: |
          npm run build
          npm run test:coverage
          npm run update:badge
      - uses: EndBug/add-and-commit@v7
        with:
          add: 'README.md'
          author_name: Update-bot
          message: 'Update README.md from update-bot'
          push: true
